# Numpy
___

Numpy (*numeric python*) é uma biblioteca usada principlamente para operações com ```arrays```. Arrays são como listas, mas que permitem uma série de operações mais complexas e que estas sejam feitas elemento a elemento eliminando a necessidade de loops no nosso código. Ela é a principal biblioteca utilizada por outras bibliotecas para lidar com dados, mais notoriamente o scikit-learn e o pandas trabalham com arrays a todo momento. Além disso, o numpy possui um conjunto vasto de funções para algebra linear, estatística e operações com matrizes.

Vamos iniciar vendo o quanto um array pode ser mais poderoso que uma lista.

In [4]:
lista_alturas = [1.4, 1.57, 1.87, 1.77, 1.71, 1.69, 1.93, 1.55]
lista_pesos = [55, 65, 87, 90, 78, 65, 57, 60]

In [5]:
## calculando IMC

[peso/(altura**2) for peso, altura in zip(lista_pesos,lista_alturas)]

[28.061224489795922,
 26.370238143535232,
 24.879178701135288,
 28.72737719046251,
 26.674874320303687,
 22.758306781975424,
 15.302424226153724,
 24.97398543184183]

In [9]:
imcs = []

for peso,altura in zip(lista_pesos,lista_alturas):
    imc = peso/(altura**2)
    imcs.append(imc)

imcs

[28.061224489795922,
 26.370238143535232,
 24.879178701135288,
 28.72737719046251,
 26.674874320303687,
 22.758306781975424,
 15.302424226153724,
 24.97398543184183]

In [10]:
lista_alturas / (lista_pesos**2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

É possível efetuar a mesma operação sem a necessidade de syntaxe adicionais que remetem a loops, basta utilizarmos ```arrays```. Para criar um array no numpy, basta utilizar a função ```.array()```.

In [15]:
import numpy as np

In [16]:
## criando os arrays

pesos = np.array(lista_pesos)
alturas = np.array(lista_alturas)

In [17]:
pesos

array([55, 65, 87, 90, 78, 65, 57, 60])

In [19]:
alturas

array([1.4 , 1.57, 1.87, 1.77, 1.71, 1.69, 1.93, 1.55])

In [20]:
## tipo

type(pesos)

numpy.ndarray

In [21]:
imcs = pesos / (alturas**2)
imcs

array([28.06122449, 26.37023814, 24.8791787 , 28.72737719, 26.67487432,
       22.75830678, 15.30242423, 24.97398543])

Perceba que o próprio numpy já se encarregou de fazer as operações elemento a elemento de cada array e como resultado nos foi dado também um array.

In [26]:
%%timeit
[peso/(altura**2) for peso, altura in zip(lista_pesos,lista_alturas)]

1.18 µs ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
%%timeit
pesos / (alturas**2)

1.28 µs ± 14.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


O numpy é rápido! Mas ele funciona bem porque assume que todos os dados em seus arrays tem o mesmo tipo. Se você tentar criar um array com vários tipos de dados é provável que o numpy transforme todos os elementos em strings.

Todos os arrays possuem características e funções que são importantes em situações do dia-a-dia.

In [28]:
pesos

array([55, 65, 87, 90, 78, 65, 57, 60])

In [29]:
## size nos dá a quantidade de elementos dentro de um array

pesos.size

8

In [30]:
## shape nos dá o formato de um array, nesta situação o array possui somente uma dimensão com 8 valores

pesos.shape

(8,)

In [31]:
## min nos dá o valor mínimo dentro do array

pesos.min()

55

In [32]:
## max nos dá o valor máximo dentro do array

pesos.max()

90

In [33]:
## argmin nos dá a posição do valor mínimo

pesos.argmin()

0

In [34]:
## argmin nos dá a posição do valor máximo

pesos.argmax()

3

In [35]:
## dtype nos dá o tipo do dado que está contido no array

pesos.dtype

dtype('int64')

# Operações com arrays
___

O comportamento das operações básicas são diferentes de acordo com o tipo de dado utilizado, por exemplo, operações com listas tem um comportamento diferentes de operações com arrays.

In [37]:
## o operador '+' concatena listas
ls  = [1,2,3,4]
ls2 = [5,6,7,8]

ls+ls2

[1, 2, 3, 4, 5, 6, 7, 8]

In [38]:
## o operador '+' soma os valores de dois arrays

arr  = np.array(ls)
arr2 = np.array(ls2)

arr+arr2

array([ 6,  8, 10, 12])

In [39]:
## subtração

arr-arr2

array([-4, -4, -4, -4])

In [40]:
## multiplicação

arr*arr2

array([ 5, 12, 21, 32])

In [41]:
## potenciação

arr**arr2

array([    1,    64,  2187, 65536])

In [42]:
## incremento

arr += arr2

In [44]:
arr -= arr2
arr

array([1, 2, 3, 4])

Também é possível mesclar operações de arrays com valores inteiros.

In [46]:
arr2

array([5, 6, 7, 8])

In [45]:
arr2*2

array([10, 12, 14, 16])

In [47]:
arr2**2

array([25, 36, 49, 64])

In [48]:
arr2/10

array([0.5, 0.6, 0.7, 0.8])

# Indexação de arrays
___

Indexar arrays é tão simples quanto indexar listas, porém arrays também recebem outros arrays booleanos para seleção e filtragem de vários valores ao mesmo tempo.

In [51]:
imcs

array([28.06122449, 26.37023814, 24.8791787 , 28.72737719, 26.67487432,
       22.75830678, 15.30242423, 24.97398543])

In [56]:
imcs[imcs.argmax()]

28.72737719046251

In [61]:
imcs[1:4]

array([26.37023814, 24.8791787 , 28.72737719])

Caso seja necessário selecionar somente os valores abaixo de 24 é possível utilizar arrays booleanos para isso, basta criar uma condição lógica e aplicar o resultado ao indexador do array original.

In [63]:
imcs

array([28.06122449, 26.37023814, 24.8791787 , 28.72737719, 26.67487432,
       22.75830678, 15.30242423, 24.97398543])

In [62]:
## criando a condição lógica

imcs < 24

array([False, False, False, False, False,  True,  True, False])

In [64]:
## passando ao array original

imcs[imcs<24]

array([22.75830678, 15.30242423])

AND -> & <br>
OR -> | <br>
NOT -> ~ <br>

In [83]:
mascara = (imcs < 24)

print(imcs < 24)

[False False False False False  True  True False]


In [94]:
imcs[mascara]

array([22.75830678, 15.30242423])

Existem somente dois imcs abaixo de 24, logo o array com o resultado da condição lógica possue somente dois valores ```True``` nas suas respectivas posições.

# Arrays de duas dimensões
___

Arrays podem possuir mais de uma dimensão, isso significa que podem ter mais de um conjunto de informações. Até agora vimos alturas e pesos divididos em 2 arrays, cada peso e altura está associado a uma pessoa, porém, é possivel criar somente um array que demonstre as duas dimensões (pessoas e caractéristicas)

In [100]:
pesos

array([55, 65, 87, 90, 78, 65, 57, 60])

In [101]:
alturas

array([1.4 , 1.57, 1.87, 1.77, 1.71, 1.69, 1.93, 1.55])

In [102]:
novo_arr = np.array([[55.  ,  1.4 ],
                    [65.  ,  1.57],
                    [87.  ,  1.87],
                    [90.  ,  1.77],
                    [78.  ,  1.71],
                    [65.  ,  1.69],
                    [57.  ,  1.93],
                    [60.  ,  1.55]])

Veja que nesse novo array mudadmos a forma de pensar e agora temos um array contendo pessoas na primeira dimensão e na segunda dimensão as características de peso e altura de cada uma das pessoas.

In [103]:
type(novo_arr)

numpy.ndarray

In [104]:
novo_arr.size

16

In [105]:
novo_arr.shape

(8, 2)

In [106]:
novo_arr

array([[55.  ,  1.4 ],
       [65.  ,  1.57],
       [87.  ,  1.87],
       [90.  ,  1.77],
       [78.  ,  1.71],
       [65.  ,  1.69],
       [57.  ,  1.93],
       [60.  ,  1.55]])

O array ```novo_arr``` possui um shape (8,2), ou seja, 16 de tamanho (size). É possível modificar o shape desse array para qualquer outro shape que também resulte em um size de 16. Para isso, bata utilizar a função ```reshape```.

In [107]:
## (8,2) -> (4,4)

novo_arr.reshape(4,4)

array([[55.  ,  1.4 , 65.  ,  1.57],
       [87.  ,  1.87, 90.  ,  1.77],
       [78.  ,  1.71, 65.  ,  1.69],
       [57.  ,  1.93, 60.  ,  1.55]])

In [108]:
## (8,2) -> (2,8)

novo_arr.reshape(2,8)

array([[55.  ,  1.4 , 65.  ,  1.57, 87.  ,  1.87, 90.  ,  1.77],
       [78.  ,  1.71, 65.  ,  1.69, 57.  ,  1.93, 60.  ,  1.55]])

In [109]:
## (8,2) -> (1,16)

novo_arr.reshape(1,16)

array([[55.  ,  1.4 , 65.  ,  1.57, 87.  ,  1.87, 90.  ,  1.77, 78.  ,
         1.71, 65.  ,  1.69, 57.  ,  1.93, 60.  ,  1.55]])

Também é possível utilizar o valor ```-1``` em alguma das dimensões na operação de reshape para "completar" o array até um size aceitável.

In [112]:
novo_arr.reshape(-1,1)

array([[55.  ],
       [ 1.4 ],
       [65.  ],
       [ 1.57],
       [87.  ],
       [ 1.87],
       [90.  ],
       [ 1.77],
       [78.  ],
       [ 1.71],
       [65.  ],
       [ 1.69],
       [57.  ],
       [ 1.93],
       [60.  ],
       [ 1.55]])

In [113]:
novo_arr.size

16

O ```novo_arr``` possui agora duas dimensões: a primeira possui 8 elementos e a segunda possui 2 elementos. O que significa que temos um tamanho (size) de 16. Também é comum utilizar esse formato de array para representar ```matrizes```.

Executar a indexação e fatiamento de arrays de duas dimensões é um pouco mais complexo, pois é necessário enviar ao indexador ```[]``` um índice para uma das dimensões, ou seja, duas dimensões, dois índices. Para exemplificar, veja o array ```jogadores``` contendo a altura e peso dos jogadores da NBA.

In [118]:
jogadores = np.load('data/jogadores_nba.npy')
jogadores

array([[213.36    , 106.59412 ],
       [210.82    , 106.59412 ],
       [208.28    , 106.59412 ],
       ...,
       [195.58    ,  97.52228 ],
       [203.2     ,  98.883056],
       [203.2     , 106.59412 ]])

In [119]:
## verificando o tamanho do array jogadores

jogadores.size

23400

In [120]:
## verificando o formato

jogadores.shape

(11700, 2)

Existem nesse array, informações de duas características (altura e peso) de mais de 11700 atletas. Para selecionar somente a altura do segundo atleta do array é necessário utilizar uma indexação complexa.

In [134]:
jogadores[:,1]

array([106.59412 , 106.59412 , 106.59412 , ...,  97.52228 ,  98.883056,
       106.59412 ])

Acima selecionamos o índice desejado em cada uma das dimensões.O primeiro número 1 significa que gostaríamos de acessar as informações do segundo jogador, e o segundo número 1 significa que gostaríamos de acessar a segunda característica dele (peso). Também é possível utilizar o ```:``` para indicar todas as informações de uma determinada dimensão.

In [ ]:
## selecionando a altura de todos os jogadores

jogadores[:,0]

In [ ]:
## selecionando o peso de todos os jogadores

jogadores[:,1]

É possível criar também condições lógicas e aplica-las a cada uma das dimensões necessárias.

In [ ]:
## selecionando jogadores que possuem um peso menor que 100 kilos

jogadores[jogadores[:,1] < 100]

In [ ]:
## selecionando jogadores que possuem altura maior que 200 e peso menor que 100 kilos

jogadores[(jogadores[:,0] > 200) & (jogadores[:,1] < 100)]

Utilizando esse método de indexação também é possível executar operações.

In [ ]:
## transformando as alturas de metros para pés

jogadores[:,0] = (jogadores[:,0]/100)*3.281
jogadores

# Funções estatísticas
___

Em seu dia-a-dia, um cientista de dados trabalho com vários conjuntos de milhares, milhões e até bilhões de observações, entender algumas características desses dados é de extrema importância para etapas inferenciais e descritivas. O numpy oferece um conjunto de funções estatísticas para nos ajudar a descrever melhor nossos conjuntos de dados.

In [ ]:
jogadores = np.load('data/jogadores_nba.npy')
jogadores

In [ ]:
## média

np.mean(jogadores[:,0])

In [ ]:
## outra forma de calcular média

jogadores[:,0].mean()

In [ ]:
## mediana

np.median(jogadores[:,0])

In [ ]:
## correlação

np.corrcoef(jogadores[:,0],jogadores[:,1])

In [ ]:
## desvio padrão

jogadores[:,0].std()

In [ ]:
## variância

jogadores[:,0].var()